# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brick Image
email: mail@brickimage.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Brick Image Ltd are a specialist brick tinting company operating both in the UK and the Netherlands.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brickimage.co.uk/" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

exclude: ['node_modules', '_scss']
keep_files: ['_site/css', '_site/js']
